name: ci
on:
  push: {}
jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Log into docker hub
        run: docker login -u mikailbag -p ${{ secrets.DOCKER_TOKEN }}
      - name: build image
        run: docker build -t mikailbag/jjs-dev:latest .
        env:
          DOCKER_BUILDKIT: 1
      - name: publish image
        run: docker push mikailbag/jjs-dev:latest

